use axum::http::{HeaderValue, Uri};
use borsh::{BorshDeserialize, BorshSerialize};
use serde::Deserialize;
use solana_sdk::hash::hashv;
use solana_sdk::pubkey::Pubkey;
use solana_sdk::signature::{read_keypair_file, Keypair, Signature};
use std::net::SocketAddr;
use std::str::FromStr;

use crate::validation::composite::ScoringConfig;

/// Protocol authority pubkey that signs `VALIDATION_SERVICE_URL` for
/// deploy-time pinning. Hardcoded so an attacker with environment-variable
/// access cannot repoint validation traffic — they can change the URL but
/// they cannot produce a signature against it from this keypair.
///
/// Devnet authority. Mainnet would compile a different binary (or guard
/// behind a feature flag) with the production authority pubkey baked in.
const VALIDATION_URL_AUTHORITY_BS58: &str = "GYm3f7DTvTZ6dN1Gfe7UowHRerxTU4FK2u1w6zVGVT3Y";

/// Domain separator for the URL signature message. Prevents a signature
/// from another tool that happens to be signed by the same authority key
/// from being a valid validator-URL signature here.
const VALIDATION_URL_DOMAIN_PREFIX: &str = "Entros-VALIDATOR-URL-V1:";
const DEFAULT_CHALLENGE_TTL_SECS: u64 = 60;
/// Limits replay exposure and live nonce retention to five minutes.
const MAX_CHALLENGE_TTL_SECS: u64 = 300;

/// Verify that `signature_bs58` is a valid Ed25519 signature by `authority`
/// over `DOMAIN_PREFIX || url`. Internal helper, exposed for tests so they
/// can sign with an ad-hoc keypair without touching the production
/// authority constant.
fn verify_url_signature_against(
    url: &str,
    signature_bs58: &str,
    authority: &Pubkey,
) -> Result<(), String> {
    let signature_bytes = bs58::decode(signature_bs58)
        .into_vec()
        .map_err(|e| format!("VALIDATION_SERVICE_URL_SIGNATURE is not valid bs58: {e}"))?;
    let signature = Signature::try_from(signature_bytes.as_slice())
        .map_err(|e| format!("VALIDATION_SERVICE_URL_SIGNATURE has invalid length: {e}"))?;
    let message = format!("{VALIDATION_URL_DOMAIN_PREFIX}{url}");
    if !signature.verify(authority.as_ref(), message.as_bytes()) {
        return Err(format!(
            "VALIDATION_SERVICE_URL_SIGNATURE does not verify against authority {authority} \
             — refusing to start with an unsigned URL"
        ));
    }
    Ok(())
}

/// Verify that `signature_bs58` is a valid Ed25519 signature by
/// `VALIDATION_URL_AUTHORITY_BS58` over `DOMAIN_PREFIX || url`.
pub fn verify_validation_url_signature(url: &str, signature_bs58: &str) -> Result<(), String> {
    let authority = Pubkey::from_str(VALIDATION_URL_AUTHORITY_BS58)
        .map_err(|e| format!("hardcoded validation URL authority is invalid: {e}"))?;
    verify_url_signature_against(url, signature_bs58, &authority)
}

pub(crate) const EXPECTED_SCORING_SERVICE: [u8; 16] = *b"entros-executor\0";
pub(crate) const EXPECTED_SCORING_CONFIG_REVISION: u64 = 1;
pub(crate) const SCORING_CONFIG_ENV_VAR: &str = "EXECUTOR_SCORING_CONFIG_BUNDLE";

const SCORING_CONFIG_AUTHORITY_BS58: Option<&str> =
    Some("8hhzuqQ7gfyKkkYs9DwCvZYgPnTYKp2duHXA3AFBDEX5");
const SCORING_CONFIG_ID_BS58: Option<&str> = Some("3rk2LtVE66iz5AeZRS8G2UyD67nMiytrF2PWTmM7aTEF");

const SCORING_CONFIG_SCHEMA_VERSION: u8 = 1;
const SCORING_CONFIG_DOMAIN: &[u8] = b"Entros\0executor-scoring-config\0v1\0";
const SCORING_CONFIG_PAYLOAD_BYTES: usize = 87;
const SCORING_CONFIG_BUNDLE_MAX_BYTES: usize = 256;

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
#[repr(u8)]
pub(crate) enum ScoringCluster {
    Devnet = 1,
}

impl ScoringCluster {
    const fn code(self) -> u8 {
        self as u8
    }
}

/// Fixed-width signed payload. Integer parts per million avoid float encoding
/// differences between the Rust verifier and the offline signing tool.
#[derive(BorshDeserialize, BorshSerialize)]
struct SignedScoringPayload {
    schema_version: u8,
    service: [u8; 16],
    cluster: u8,
    environment: u8,
    revision: u64,
    audit_nonce: [u8; 32],
    biometric_ppm: u32,
    tts_ppm: u32,
    unallocated_ppm: u32,
    automation_ppm: u32,
    reputation_ppm: u32,
    friction_threshold_ppm: u32,
    reject_threshold_ppm: u32,
}

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub(crate) enum ScoringConfigSource {
    DevelopmentDefault,
    Signed,
}

/// Opaque identifier safe for startup logs. The signed payload contains a
/// nonce generated by the signing tool, so this digest does not expose the
/// low-entropy policy values.
#[derive(Clone, Debug, Eq, PartialEq)]
pub(crate) struct ScoringConfigId(String);

impl ScoringConfigId {
    pub(crate) fn as_str(&self) -> &str {
        &self.0
    }

    fn parse_compiled(value: &str) -> Result<Self, String> {
        let decoded = bs58::decode(value)
            .into_vec()
            .map_err(|_| "compiled scoring config ID is not valid base58".to_string())?;
        if decoded.len() != 32 || bs58::encode(decoded).into_string() != value {
            return Err("compiled scoring config ID is not a canonical 32-byte value".to_string());
        }
        Ok(Self(value.to_string()))
    }
}

#[derive(Debug)]
pub(crate) struct ResolvedScoringConfig {
    pub(crate) config: ScoringConfig,
    pub(crate) revision: u64,
    pub(crate) config_id: ScoringConfigId,
    pub(crate) source: ScoringConfigSource,
}

pub(crate) struct ScoringConfigRequirements {
    pub(crate) authority: Pubkey,
    pub(crate) config_id: ScoringConfigId,
    pub(crate) service: [u8; 16],
    pub(crate) cluster: ScoringCluster,
    pub(crate) environment: Environment,
    pub(crate) revision: u64,
}

/// Resolve the configured scoring policy without reading process state.
/// Production always requires a signed bundle. Development may use the neutral
/// public default only when no bundle was supplied.
pub(crate) fn resolve_scoring_config(
    bundle: Option<&str>,
    requirements: &ScoringConfigRequirements,
) -> Result<ResolvedScoringConfig, String> {
    let Some(bundle) = bundle else {
        if requirements.environment.is_prod() {
            return Err(format!(
                "{SCORING_CONFIG_ENV_VAR} is required when ENVIRONMENT=prod"
            ));
        }
        return Ok(ResolvedScoringConfig {
            config: ScoringConfig::development_default(),
            revision: 0,
            config_id: ScoringConfigId("development-default".into()),
            source: ScoringConfigSource::DevelopmentDefault,
        });
    };

    if bundle.len() > SCORING_CONFIG_BUNDLE_MAX_BYTES {
        return Err(format!(
            "{SCORING_CONFIG_ENV_VAR} exceeds the maximum encoded size"
        ));
    }
    if !bundle.is_ascii() {
        return Err(format!(
            "{SCORING_CONFIG_ENV_VAR} must contain ASCII base58 data"
        ));
    }

    let mut parts = bundle.split('.');
    let payload_bs58 = parts.next().unwrap_or_default();
    let signature_bs58 = parts
        .next()
        .ok_or_else(|| format!("{SCORING_CONFIG_ENV_VAR} must contain payload.signature"))?;
    if payload_bs58.is_empty() || signature_bs58.is_empty() || parts.next().is_some() {
        return Err(format!(
            "{SCORING_CONFIG_ENV_VAR} must contain exactly one payload.signature pair"
        ));
    }

    let payload_bytes = decode_canonical_base58(payload_bs58, "payload")?;
    if payload_bytes.len() != SCORING_CONFIG_PAYLOAD_BYTES {
        return Err(format!(
            "{SCORING_CONFIG_ENV_VAR} payload has an invalid length"
        ));
    }
    let signature_bytes = decode_canonical_base58(signature_bs58, "signature")?;
    let signature = Signature::try_from(signature_bytes.as_slice())
        .map_err(|_| format!("{SCORING_CONFIG_ENV_VAR} signature has an invalid length"))?;

    let mut signed_message = Vec::with_capacity(SCORING_CONFIG_DOMAIN.len() + payload_bytes.len());
    signed_message.extend_from_slice(SCORING_CONFIG_DOMAIN);
    signed_message.extend_from_slice(&payload_bytes);
    if !signature.verify(requirements.authority.as_ref(), &signed_message) {
        return Err(format!(
            "{SCORING_CONFIG_ENV_VAR} signature does not verify against the scoring authority"
        ));
    }

    let payload: SignedScoringPayload = borsh::from_slice(&payload_bytes)
        .map_err(|_| format!("{SCORING_CONFIG_ENV_VAR} payload is malformed"))?;
    validate_scoring_binding(&payload, requirements)?;

    if payload.audit_nonce.iter().all(|byte| *byte == 0) {
        return Err(format!(
            "{SCORING_CONFIG_ENV_VAR} audit nonce must not be all zeroes"
        ));
    }

    let config = ScoringConfig::try_new(
        payload.biometric_ppm,
        payload.tts_ppm,
        payload.unallocated_ppm,
        payload.automation_ppm,
        payload.reputation_ppm,
        payload.friction_threshold_ppm,
        payload.reject_threshold_ppm,
    )
    .map_err(|_| format!("{SCORING_CONFIG_ENV_VAR} policy invariants are invalid"))?;

    let config_id = ScoringConfigId(hashv(&[SCORING_CONFIG_DOMAIN, &payload_bytes]).to_string());
    if config_id != requirements.config_id {
        return Err(format!(
            "{SCORING_CONFIG_ENV_VAR} config ID does not match this release"
        ));
    }

    Ok(ResolvedScoringConfig {
        config,
        revision: payload.revision,
        config_id,
        source: ScoringConfigSource::Signed,
    })
}

fn decode_canonical_base58(value: &str, field: &str) -> Result<Vec<u8>, String> {
    let decoded = bs58::decode(value)
        .into_vec()
        .map_err(|_| format!("{SCORING_CONFIG_ENV_VAR} {field} is not valid base58"))?;
    if bs58::encode(&decoded).into_string() != value {
        return Err(format!(
            "{SCORING_CONFIG_ENV_VAR} {field} must use canonical base58"
        ));
    }
    Ok(decoded)
}

fn validate_scoring_binding(
    payload: &SignedScoringPayload,
    requirements: &ScoringConfigRequirements,
) -> Result<(), String> {
    if payload.schema_version != SCORING_CONFIG_SCHEMA_VERSION {
        return Err(format!(
            "{SCORING_CONFIG_ENV_VAR} schema version is not supported"
        ));
    }
    if payload.service != requirements.service {
        return Err(format!(
            "{SCORING_CONFIG_ENV_VAR} service binding does not match"
        ));
    }
    if payload.cluster != requirements.cluster.code() {
        return Err(format!(
            "{SCORING_CONFIG_ENV_VAR} cluster binding does not match"
        ));
    }
    if payload.environment != requirements.environment.scoring_code() {
        return Err(format!(
            "{SCORING_CONFIG_ENV_VAR} environment binding does not match"
        ));
    }
    if payload.revision != requirements.revision {
        return Err(format!(
            "{SCORING_CONFIG_ENV_VAR} revision binding does not match"
        ));
    }
    Ok(())
}

/// Read a boolean env var with lenient truthy/falsy spellings. An unset or
/// unrecognized value returns `default`, so a typo never silently flips an
/// observe-first flag off.
fn parse_bool_env(key: &str, default: bool) -> bool {
    parse_bool(std::env::var(key).ok().as_deref(), default)
}

/// Pure core of [`parse_bool_env`], split out so the spelling rules are unit
/// testable without touching process env.
fn parse_bool(value: Option<&str>, default: bool) -> bool {
    match value {
        None => default,
        Some(s) => match s.trim().to_ascii_lowercase().as_str() {
            "1" | "true" | "yes" | "on" => true,
            "0" | "false" | "no" | "off" => false,
            _ => default,
        },
    }
}

fn parse_challenge_ttl_secs(value: Option<&str>) -> Result<u64, String> {
    let ttl_secs = match value {
        Some(value) => value
            .parse()
            .map_err(|e| format!("CHALLENGE_TTL_SECS is not a valid u64: {e}"))?,
        None => DEFAULT_CHALLENGE_TTL_SECS,
    };
    if !(1..=MAX_CHALLENGE_TTL_SECS).contains(&ttl_secs) {
        return Err(format!(
            "CHALLENGE_TTL_SECS must be between 1 and {MAX_CHALLENGE_TTL_SECS}"
        ));
    }
    Ok(ttl_secs)
}

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum Environment {
    Dev,
    Prod,
}

impl Environment {
    fn parse(value: Option<&str>) -> Result<Self, String> {
        match value.unwrap_or("dev") {
            "dev" => Ok(Self::Dev),
            "prod" => Ok(Self::Prod),
            other => Err(format!(
                "ENVIRONMENT must be either dev or prod, got {other:?}"
            )),
        }
    }

    pub fn is_prod(self) -> bool {
        self == Self::Prod
    }

    const fn scoring_code(self) -> u8 {
        match self {
            Self::Dev => 1,
            Self::Prod => 2,
        }
    }
}

fn parse_cors_origins(
    values: Vec<String>,
    environment: Environment,
) -> Result<Vec<HeaderValue>, String> {
    if environment.is_prod() && values.is_empty() {
        return Err("CORS_ORIGINS must contain at least one origin when ENVIRONMENT=prod".into());
    }

    values
        .into_iter()
        .map(|value| {
            let uri: Uri = value
                .parse()
                .map_err(|_| format!("CORS_ORIGINS contains an invalid origin: {value:?}"))?;
            let valid_scheme = matches!(uri.scheme_str(), Some("http" | "https"));
            let valid_path = uri.path() == "/" && uri.query().is_none();
            if !valid_scheme || uri.authority().is_none() || !valid_path {
                return Err(format!(
                    "CORS_ORIGINS entries must be HTTP origins without paths: {value:?}"
                ));
            }
            HeaderValue::from_str(&value)
                .map_err(|_| format!("CORS_ORIGINS contains an invalid header value: {value:?}"))
        })
        .collect()
}

#[cfg(test)]
mod tests {
    use super::*;
    use solana_sdk::signer::Signer;

    #[test]
    fn parse_bool_handles_spellings_and_keeps_default_on_unknown() {
        assert!(parse_bool(Some("TRUE"), false));
        assert!(parse_bool(Some(" on "), false));
        assert!(parse_bool(Some("1"), false));
        assert!(!parse_bool(Some("off"), true));
        assert!(!parse_bool(Some("0"), true));
        // Unset and unrecognized both fall back to the caller's default.
        assert!(parse_bool(None, true));
        assert!(!parse_bool(None, false));
        assert!(parse_bool(Some("garbage"), true));
        assert!(!parse_bool(Some("garbage"), false));
    }

    #[test]
    fn environment_rejects_unknown_values() {
        assert_eq!(Environment::parse(None).unwrap(), Environment::Dev);
        assert_eq!(Environment::parse(Some("dev")).unwrap(), Environment::Dev);
        assert_eq!(Environment::parse(Some("prod")).unwrap(), Environment::Prod);
        assert!(Environment::parse(Some("production")).is_err());
        assert!(Environment::parse(Some("Prod")).is_err());
    }

    #[test]
    fn production_requires_valid_cors_origins() {
        assert!(parse_cors_origins(Vec::new(), Environment::Prod).is_err());
        assert!(parse_cors_origins(vec!["*".into()], Environment::Prod).is_err());
        assert!(
            parse_cors_origins(vec!["https://entros.io/path".into()], Environment::Prod).is_err()
        );

        let parsed = parse_cors_origins(
            vec!["https://entros.io".into(), "http://localhost:3000".into()],
            Environment::Prod,
        )
        .unwrap();
        assert_eq!(parsed.len(), 2);
    }

    #[test]
    fn development_can_use_permissive_cors() {
        assert!(parse_cors_origins(Vec::new(), Environment::Dev)
            .unwrap()
            .is_empty());
    }

    fn sign(authority: &Keypair, url: &str) -> String {
        let message = format!("{VALIDATION_URL_DOMAIN_PREFIX}{url}");
        bs58::encode(authority.sign_message(message.as_bytes()).as_ref()).into_string()
    }

    #[test]
    fn hardcoded_authority_constant_is_well_formed() {
        Pubkey::from_str(VALIDATION_URL_AUTHORITY_BS58)
            .expect("VALIDATION_URL_AUTHORITY_BS58 must parse as a valid Solana pubkey");
    }

    #[test]
    fn accepts_signature_from_authority() {
        let authority = Keypair::new();
        let url = "http://validator.example:8080";
        let sig = sign(&authority, url);
        verify_url_signature_against(url, &sig, &authority.pubkey()).unwrap();
    }

    #[test]
    fn rejects_signature_for_different_url() {
        let authority = Keypair::new();
        let sig = sign(&authority, "http://attacker.example");
        assert!(verify_url_signature_against(
            "http://validator.example",
            &sig,
            &authority.pubkey(),
        )
        .is_err());
    }

    #[test]
    fn rejects_signature_from_wrong_authority() {
        let authority = Keypair::new();
        let other = Keypair::new();
        let url = "http://validator.example";
        let sig = sign(&authority, url);
        assert!(verify_url_signature_against(url, &sig, &other.pubkey()).is_err());
    }

    #[test]
    fn rejects_malformed_bs58() {
        let authority = Keypair::new();
        assert!(
            verify_url_signature_against("http://x", "not-valid-bs58!!!", &authority.pubkey())
                .is_err()
        );
    }

    #[test]
    fn rejects_wrong_length_signature() {
        let authority = Keypair::new();
        let too_short = bs58::encode([0u8; 32]).into_string();
        assert!(verify_url_signature_against("http://x", &too_short, &authority.pubkey()).is_err());
    }

    #[test]
    fn domain_prefix_blocks_signatures_for_other_payloads() {
        // A signature over the URL alone (without DOMAIN_PREFIX) must not
        // verify, even with the right authority — domain separation is the
        // whole point of the prefix.
        let authority = Keypair::new();
        let url = "http://validator.example";
        let bare = bs58::encode(authority.sign_message(url.as_bytes()).as_ref()).into_string();
        assert!(verify_url_signature_against(url, &bare, &authority.pubkey()).is_err());
    }

    fn synthetic_scoring_payload() -> SignedScoringPayload {
        SignedScoringPayload {
            schema_version: SCORING_CONFIG_SCHEMA_VERSION,
            service: EXPECTED_SCORING_SERVICE,
            cluster: ScoringCluster::Devnet.code(),
            environment: Environment::Prod.scoring_code(),
            revision: EXPECTED_SCORING_CONFIG_REVISION,
            audit_nonce: [0x5a; 32],
            biometric_ppm: 110_000,
            tts_ppm: 170_000,
            unallocated_ppm: 200_000,
            automation_ppm: 230_000,
            reputation_ppm: 290_000,
            friction_threshold_ppm: 400_000,
            reject_threshold_ppm: 700_000,
        }
    }

    fn scoring_requirements(authority: &Keypair) -> ScoringConfigRequirements {
        ScoringConfigRequirements {
            authority: authority.pubkey(),
            config_id: scoring_config_id(&synthetic_scoring_payload()),
            service: EXPECTED_SCORING_SERVICE,
            cluster: ScoringCluster::Devnet,
            environment: Environment::Prod,
            revision: EXPECTED_SCORING_CONFIG_REVISION,
        }
    }

    fn scoring_config_id(payload: &SignedScoringPayload) -> ScoringConfigId {
        let payload_bytes = borsh::to_vec(payload).expect("serialize scoring payload");
        ScoringConfigId(hashv(&[SCORING_CONFIG_DOMAIN, &payload_bytes]).to_string())
    }

    fn scoring_bundle_with_domain(
        authority: &Keypair,
        payload: &SignedScoringPayload,
        domain: &[u8],
    ) -> String {
        let payload_bytes = borsh::to_vec(payload).expect("serialize scoring payload");
        assert_eq!(payload_bytes.len(), SCORING_CONFIG_PAYLOAD_BYTES);
        let mut message = Vec::with_capacity(domain.len() + payload_bytes.len());
        message.extend_from_slice(domain);
        message.extend_from_slice(&payload_bytes);
        let signature = authority.sign_message(&message);
        format!(
            "{}.{}",
            bs58::encode(payload_bytes).into_string(),
            bs58::encode(signature.as_ref()).into_string()
        )
    }

    fn scoring_bundle(authority: &Keypair, payload: &SignedScoringPayload) -> String {
        scoring_bundle_with_domain(authority, payload, SCORING_CONFIG_DOMAIN)
    }

    #[test]
    fn signed_scoring_payload_has_the_fixed_wire_size() {
        let bytes = borsh::to_vec(&synthetic_scoring_payload()).unwrap();
        assert_eq!(bytes.len(), SCORING_CONFIG_PAYLOAD_BYTES);
    }

    #[test]
    fn scoring_payload_matches_the_signer_wire_fixture() {
        let authority = Keypair::new();
        let payload = SignedScoringPayload {
            schema_version: SCORING_CONFIG_SCHEMA_VERSION,
            service: EXPECTED_SCORING_SERVICE,
            cluster: ScoringCluster::Devnet.code(),
            environment: Environment::Dev.scoring_code(),
            revision: EXPECTED_SCORING_CONFIG_REVISION,
            audit_nonce: std::array::from_fn(|index| index as u8),
            biometric_ppm: 111_111,
            tts_ppm: 222_222,
            unallocated_ppm: 333_333,
            automation_ppm: 123_456,
            reputation_ppm: 209_878,
            friction_threshold_ppm: 123_456,
            reject_threshold_ppm: 654_321,
        };
        let payload_bytes = borsh::to_vec(&payload).expect("serialize scoring payload");
        let payload_hex = payload_bytes
            .iter()
            .map(|byte| format!("{byte:02x}"))
            .collect::<String>();
        assert_eq!(
            payload_hex,
            "01656e74726f732d6578656375746f720001010100000000000000000102030405060708090a0b0c0d0e0f101112131415161718191a1b1c1d1e1f07b201000e6403001516050040e20100d633030040e20100f1fb0900"
        );

        let bundle = scoring_bundle(&authority, &payload);
        let mut requirements = scoring_requirements(&authority);
        requirements.environment = Environment::Dev;
        requirements.config_id = scoring_config_id(&payload);
        let resolved = resolve_scoring_config(Some(&bundle), &requirements)
            .expect("the shared signer fixture must resolve");
        assert_eq!(
            resolved.config_id.as_str(),
            "2xErAkDVeReZF517Qroi2UaDxMtnUh75yqFzz71dnh9A"
        );
    }

    #[test]
    fn resolves_a_bound_signed_scoring_config() {
        let authority = Keypair::new();
        let bundle = scoring_bundle(&authority, &synthetic_scoring_payload());
        let resolved = resolve_scoring_config(Some(&bundle), &scoring_requirements(&authority))
            .expect("signed fixture must resolve");

        assert_eq!(resolved.revision, EXPECTED_SCORING_CONFIG_REVISION);
        assert_eq!(resolved.source, ScoringConfigSource::Signed);
        assert_eq!(
            bs58::decode(resolved.config_id.as_str())
                .into_vec()
                .expect("config ID must use base58")
                .len(),
            32
        );
        assert_ne!(resolved.config_id.as_str(), "development-default");
    }

    #[test]
    fn development_uses_the_public_default_only_when_bundle_is_absent() {
        let authority = Keypair::new();
        let mut requirements = scoring_requirements(&authority);
        requirements.environment = Environment::Dev;
        let resolved = resolve_scoring_config(None, &requirements).unwrap();

        assert_eq!(resolved.revision, 0);
        assert_eq!(resolved.source, ScoringConfigSource::DevelopmentDefault);
        assert_eq!(resolved.config_id.as_str(), "development-default");
    }

    #[test]
    fn production_refuses_a_missing_signed_scoring_config() {
        let authority = Keypair::new();
        let error = resolve_scoring_config(None, &scoring_requirements(&authority)).unwrap_err();
        assert!(error.contains("required"));
    }

    #[test]
    fn bundle_parser_requires_one_nonempty_pair_within_the_size_bound() {
        let authority = Keypair::new();
        let requirements = scoring_requirements(&authority);
        for malformed in [
            "",
            "payload",
            ".signature",
            "payload.",
            "a.b.c",
            "é.signature",
        ] {
            assert!(resolve_scoring_config(Some(malformed), &requirements).is_err());
        }

        let oversized = format!("{}.{}", "1".repeat(180), "1".repeat(90));
        let error = resolve_scoring_config(Some(&oversized), &requirements).unwrap_err();
        assert!(error.contains("maximum encoded size"));
    }

    #[test]
    fn bundle_parser_rejects_non_base58_and_wrong_lengths() {
        let authority = Keypair::new();
        let requirements = scoring_requirements(&authority);
        let valid = scoring_bundle(&authority, &synthetic_scoring_payload());
        let (_, signature) = valid.split_once('.').unwrap();
        assert!(resolve_scoring_config(Some(&format!("0.{signature}")), &requirements).is_err());

        let short_payload = bs58::encode([1u8; 8]).into_string();
        assert!(resolve_scoring_config(
            Some(&format!("{short_payload}.{signature}")),
            &requirements,
        )
        .is_err());

        let payload = valid.split_once('.').unwrap().0;
        let short_signature = bs58::encode([2u8; 32]).into_string();
        assert!(resolve_scoring_config(
            Some(&format!("{payload}.{short_signature}")),
            &requirements,
        )
        .is_err());
    }

    #[test]
    fn bounded_malformed_bundle_corpus_never_panics() {
        let authority = Keypair::new();
        let requirements = scoring_requirements(&authority);
        let alphabet = b".123456789ABCDEFGHJKLMNPQRSTUVWXYZabcdefghijkmnopqrstuvwxyz!0";
        let mut state = 0x9e37_79b9_u32;

        for case in 0..10_000_u32 {
            state = state.wrapping_mul(1_664_525).wrapping_add(1_013_904_223);
            let length = (state as usize + case as usize) % (SCORING_CONFIG_BUNDLE_MAX_BYTES + 1);
            let mut candidate = String::with_capacity(length);
            for _ in 0..length {
                state = state.wrapping_mul(1_664_525).wrapping_add(1_013_904_223);
                candidate.push(alphabet[state as usize % alphabet.len()] as char);
            }
            let _ = resolve_scoring_config(Some(&candidate), &requirements);
        }
    }

    #[test]
    fn signature_binds_payload_domain_and_authority() {
        let authority = Keypair::new();
        let other = Keypair::new();
        let payload = synthetic_scoring_payload();
        let requirements = scoring_requirements(&authority);

        let wrong_domain = scoring_bundle_with_domain(&authority, &payload, b"other-domain");
        assert!(resolve_scoring_config(Some(&wrong_domain), &requirements).is_err());

        let wrong_authority = scoring_bundle(&other, &payload);
        assert!(resolve_scoring_config(Some(&wrong_authority), &requirements).is_err());

        let valid = scoring_bundle(&authority, &payload);
        let (payload_bs58, signature_bs58) = valid.split_once('.').unwrap();
        let mut tampered = bs58::decode(payload_bs58).into_vec().unwrap();
        *tampered.last_mut().unwrap() ^= 1;
        let tampered_bundle = format!(
            "{}.{}",
            bs58::encode(tampered).into_string(),
            signature_bs58
        );
        assert!(resolve_scoring_config(Some(&tampered_bundle), &requirements).is_err());
    }

    #[test]
    fn signed_binding_must_match_every_expected_dimension() {
        let authority = Keypair::new();
        let requirements = scoring_requirements(&authority);

        let mut cases = Vec::new();
        let mut schema = synthetic_scoring_payload();
        schema.schema_version += 1;
        cases.push(schema);
        let mut service = synthetic_scoring_payload();
        service.service[0] ^= 1;
        cases.push(service);
        let mut cluster = synthetic_scoring_payload();
        cluster.cluster = 2;
        cases.push(cluster);
        let mut environment = synthetic_scoring_payload();
        environment.environment = Environment::Dev.scoring_code();
        cases.push(environment);
        let mut revision = synthetic_scoring_payload();
        revision.revision += 1;
        cases.push(revision);

        for payload in cases {
            let bundle = scoring_bundle(&authority, &payload);
            assert!(resolve_scoring_config(Some(&bundle), &requirements).is_err());
        }
    }

    #[test]
    fn signed_config_requires_a_nonzero_audit_nonce() {
        let authority = Keypair::new();
        let mut payload = synthetic_scoring_payload();
        payload.audit_nonce = [0; 32];
        let bundle = scoring_bundle(&authority, &payload);
        let error =
            resolve_scoring_config(Some(&bundle), &scoring_requirements(&authority)).unwrap_err();
        assert!(error.contains("audit nonce"));
    }

    #[test]
    fn signed_config_rejects_invalid_numeric_invariants() {
        let authority = Keypair::new();
        let requirements = scoring_requirements(&authority);

        let mut wrong_budget = synthetic_scoring_payload();
        wrong_budget.biometric_ppm += 1;
        let wrong_budget_bundle = scoring_bundle(&authority, &wrong_budget);
        assert!(resolve_scoring_config(Some(&wrong_budget_bundle), &requirements).is_err());

        let mut inverted = synthetic_scoring_payload();
        inverted.friction_threshold_ppm = inverted.reject_threshold_ppm;
        let inverted_bundle = scoring_bundle(&authority, &inverted);
        assert!(resolve_scoring_config(Some(&inverted_bundle), &requirements).is_err());
    }

    #[test]
    fn signed_config_requires_both_thresholds_to_be_reachable() {
        let authority = Keypair::new();
        let requirements = scoring_requirements(&authority);

        let mut unreachable_friction = synthetic_scoring_payload();
        unreachable_friction.friction_threshold_ppm = 801_000;
        unreachable_friction.reject_threshold_ppm = 900_000;
        let bundle = scoring_bundle(&authority, &unreachable_friction);
        assert!(resolve_scoring_config(Some(&bundle), &requirements).is_err());

        for reject_threshold_ppm in [800_000, 900_000] {
            let mut unreachable_reject = synthetic_scoring_payload();
            unreachable_reject.reject_threshold_ppm = reject_threshold_ppm;
            let bundle = scoring_bundle(&authority, &unreachable_reject);
            assert!(resolve_scoring_config(Some(&bundle), &requirements).is_err());
        }
    }

    #[test]
    fn thresholds_may_approach_the_active_maximum() {
        let authority = Keypair::new();
        let mut payload = synthetic_scoring_payload();
        payload.friction_threshold_ppm = 799_998;
        payload.reject_threshold_ppm = 799_999;
        let bundle = scoring_bundle(&authority, &payload);
        let requirements = ScoringConfigRequirements {
            config_id: scoring_config_id(&payload),
            ..scoring_requirements(&authority)
        };

        resolve_scoring_config(Some(&bundle), &requirements)
            .expect("both decision boundaries remain reachable below the active maximum");
    }

    #[test]
    fn config_id_is_stable_opaque_and_nonce_bound() {
        let authority = Keypair::new();
        let requirements = scoring_requirements(&authority);
        let first_payload = synthetic_scoring_payload();
        let first_bundle = scoring_bundle(&authority, &first_payload);
        let first = resolve_scoring_config(Some(&first_bundle), &requirements).unwrap();
        let repeated = resolve_scoring_config(Some(&first_bundle), &requirements).unwrap();
        assert_eq!(first.config_id, repeated.config_id);

        let mut second_payload = synthetic_scoring_payload();
        second_payload.audit_nonce[0] ^= 1;
        let second_bundle = scoring_bundle(&authority, &second_payload);
        let mut second_requirements = scoring_requirements(&authority);
        second_requirements.config_id = scoring_config_id(&second_payload);
        let second = resolve_scoring_config(Some(&second_bundle), &second_requirements).unwrap();
        assert_ne!(first.config_id, second.config_id);
        assert_ne!(
            first.config_id.as_str(),
            first_bundle.split_once('.').unwrap().0
        );
    }

    #[test]
    fn a_release_rejects_another_valid_bundle_at_the_same_revision() {
        let authority = Keypair::new();
        let approved_payload = synthetic_scoring_payload();
        let mut other_payload = synthetic_scoring_payload();
        other_payload.audit_nonce[0] ^= 1;
        let other_bundle = scoring_bundle(&authority, &other_payload);
        let requirements = ScoringConfigRequirements {
            config_id: scoring_config_id(&approved_payload),
            ..scoring_requirements(&authority)
        };

        let error = resolve_scoring_config(Some(&other_bundle), &requirements)
            .expect_err("a different bundle must not replay within one release");
        assert!(error.contains("config ID does not match"));
    }

    #[test]
    fn compiled_config_ids_must_be_canonical_hashes() {
        let valid = "2xErAkDVeReZF517Qroi2UaDxMtnUh75yqFzz71dnh9A";
        assert_eq!(
            ScoringConfigId::parse_compiled(valid).unwrap().as_str(),
            valid
        );
        for invalid in ["", "0", "1111111111111111111111111111111"] {
            assert!(ScoringConfigId::parse_compiled(invalid).is_err());
        }
    }

    #[test]
    fn scoring_errors_never_echo_the_bundle() {
        let authority = Keypair::new();
        let requirements = scoring_requirements(&authority);
        let bundle = scoring_bundle(&Keypair::new(), &synthetic_scoring_payload());
        let error = resolve_scoring_config(Some(&bundle), &requirements).unwrap_err();
        assert!(!error.contains(&bundle));
    }

    #[test]
    fn resolved_config_debug_output_redacts_policy_values() {
        let authority = Keypair::new();
        let bundle = scoring_bundle(&authority, &synthetic_scoring_payload());
        let resolved = resolve_scoring_config(Some(&bundle), &scoring_requirements(&authority))
            .expect("signed fixture must resolve");
        let debug = format!("{resolved:?}");

        assert!(debug.contains("[REDACTED]"));
        assert!(!debug.contains("110000"));
        assert!(!debug.contains("400000"));
    }

    #[test]
    fn challenge_ttl_defaults_and_accepts_the_bounded_range() {
        assert_eq!(parse_challenge_ttl_secs(None).unwrap(), 60);
        assert_eq!(parse_challenge_ttl_secs(Some("1")).unwrap(), 1);
        assert_eq!(parse_challenge_ttl_secs(Some("300")).unwrap(), 300);
    }

    #[test]
    fn challenge_ttl_rejects_zero_oversized_and_malformed_values() {
        for value in ["0", "301", "not-a-number"] {
            assert!(parse_challenge_ttl_secs(Some(value)).is_err());
        }
    }
}

#[derive(Deserialize)]
pub struct IntegratorConfig {
    pub api_key: String,
    pub name: String,
    pub quota: u64,
}

pub struct Config {
    pub environment: Environment,
    pub rpc_url: String,
    pub validation_identity_program: Pubkey,
    pub ws_url: String,
    pub relayer_keypair: Keypair,
    pub sas_authority_keypair: Option<Keypair>,
    pub listen_addr: SocketAddr,
    pub api_keys: Vec<String>,
    pub rate_limit_per_minute: u32,
    pub study_rate_limit_per_minute: u32,
    pub study_max_in_flight: usize,
    /// Per-IP request cap across wallets and API keys.
    /// Railway supplies the client address through `X-Real-IP`.
    pub per_ip_rate_limit_per_minute: u32,
    pub integrators: Vec<IntegratorConfig>,
    pub cors_origins: Vec<HeaderValue>,
    pub sas_credential_pda: Option<Pubkey>,
    pub sas_schema_pda: Option<Pubkey>,
    pub sas_attestation_ttl_days: u64,
    pub validation_service_url: Option<String>,
    /// Ed25519 signature (bs58-encoded) over `Entros-VALIDATOR-URL-V1:<url>`
    /// signed by the protocol authority. Verified against
    /// `VALIDATION_URL_AUTHORITY_BS58` on startup when `ENVIRONMENT=prod`.
    pub validation_service_url_signature: Option<String>,
    pub validation_api_key: Option<String>,
    /// Challenge lifetime in seconds. Startup accepts values from 1 through 300.
    pub challenge_ttl_secs: u64,
    /// Per-wallet validation-attempt cap. Soft cap on
    /// the number of attempts a single wallet can make in the configured
    /// window before being rate-limited. Successful attempts refund their
    /// slot; only failures persist against the cap. Configurable via
    /// `VALIDATION_WALLET_MAX_ATTEMPTS`. Default 5 — permissive enough
    /// for legit users with borderline mics / accents to retry, tight
    /// enough to bound per-wallet retry damage.
    pub wallet_max_attempts: u8,
    /// Sliding-window length for `wallet_max_attempts`. Configurable via
    /// `VALIDATION_WALLET_WINDOW_SECS`. Default 3600 (1 hour).
    pub wallet_window_secs: u64,
    /// Observe-only automation-detection logging.
    /// When true, the `/validate-features` handler logs the client-collected
    /// automation signal for calibration — it never affects the verification
    /// decision either way. Configurable via `EXECUTOR_AUTOMATION_OBSERVE`.
    /// Default true (observe-first).
    pub automation_observe: bool,
    /// Automation hard gate. When true, a request reporting
    /// navigator.webdriver === true is rejected outright (prod only — no effect
    /// on the dev pass-through with no validator configured). Disable for the
    /// team's own E2E automation via `EXECUTOR_AUTOMATION_WEBDRIVER_REJECT`.
    /// Default true. Client-reported, so it stops lazy automation, not a
    /// determined attacker who hides the flag — the biometric pipeline is the
    /// backstop.
    pub automation_webdriver_reject: bool,
    /// Observe-only wallet-reputation logging.
    /// When true, the `/validate-features` handler reads the verifying wallet's
    /// public on-chain reputation (balance + recent activity) in a detached task
    /// and logs it for calibration — it never affects the verification decision,
    /// quota, or latency. Configurable via `EXECUTOR_WALLET_REPUTATION_OBSERVE`.
    /// Default true (observe-first).
    pub wallet_reputation_observe: bool,
    /// Observe-only curve-trace region/kinematics logging (touch-curve Stage 1).
    /// When true, `/validate-features` scores the client's coarse curve-trace
    /// outline against the issued curve (region proximity + gesture speed/nature)
    /// and logs it for calibration — it never affects the verification decision.
    /// Configurable via `EXECUTOR_CURVE_TRACE_OBSERVE`. Default true (observe-first).
    pub curve_trace_observe: bool,
    /// Cross-wallet verification cooldown duration in seconds.
    /// Configurable via `VALIDATION_CROSS_WALLET_COOLDOWN_SECS`. Default 86400 (24h).
    pub cross_wallet_cooldown_secs: u64,
    /// Enforces cross-wallet cooldown blocks when true. When false, overlaps are
    /// logged but verification proceeds. Configurable via `VALIDATION_CROSS_WALLET_COOLDOWN_ENFORCE`.
    /// Default false (observe-only for NAT/shared-network safety).
    pub cross_wallet_cooldown_enforce: bool,
    pub scoring_config: ResolvedScoringConfig,
}

impl Config {
    pub fn from_env() -> Result<Self, Box<dyn std::error::Error>> {
        let environment = Environment::parse(std::env::var("ENVIRONMENT").ok().as_deref())?;
        if !cfg!(debug_assertions) && !environment.is_prod() {
            return Err("release builds require ENVIRONMENT=prod".into());
        }

        let scoring_bundle = std::env::var(SCORING_CONFIG_ENV_VAR).ok();
        let development_fallback =
            cfg!(debug_assertions) && !environment.is_prod() && scoring_bundle.is_none();
        let scoring_authority = match SCORING_CONFIG_AUTHORITY_BS58 {
            Some(value) => Pubkey::from_str(value)
                .map_err(|_| "compiled scoring authority is not a valid public key")?,
            None if development_fallback => Pubkey::default(),
            None => return Err("this build has no configured scoring authority".into()),
        };
        let scoring_config_id = match SCORING_CONFIG_ID_BS58 {
            Some(value) => ScoringConfigId::parse_compiled(value)?,
            None if development_fallback => ScoringConfigId("development-default".into()),
            None => return Err("this build has no pinned scoring config ID".into()),
        };
        let scoring_config = resolve_scoring_config(
            scoring_bundle.as_deref(),
            &ScoringConfigRequirements {
                authority: scoring_authority,
                config_id: scoring_config_id,
                service: EXPECTED_SCORING_SERVICE,
                cluster: ScoringCluster::Devnet,
                environment,
                revision: EXPECTED_SCORING_CONFIG_REVISION,
            },
        )?;

        let rpc_url =
            std::env::var("RPC_URL").unwrap_or_else(|_| "https://api.devnet.solana.com".into());

        let ws_url =
            std::env::var("WS_URL").unwrap_or_else(|_| "wss://api.devnet.solana.com".into());

        let relayer_keypair = if let Ok(json) = std::env::var("RELAYER_KEYPAIR") {
            let bytes: Vec<u8> = serde_json::from_str(&json)
                .map_err(|e| format!("RELAYER_KEYPAIR is not valid JSON: {e}"))?;
            Keypair::try_from(bytes.as_slice())
                .map_err(|e| format!("RELAYER_KEYPAIR contains invalid keypair: {e}"))?
        } else {
            let keypair_path = std::env::var("RELAYER_KEYPAIR_PATH")
                .unwrap_or_else(|_| "./relayer-keypair.json".into());
            read_keypair_file(&keypair_path)
                .map_err(|e| format!("Failed to read keypair from {keypair_path}: {e}"))?
        };

        let listen_addr: SocketAddr = if let Ok(port) = std::env::var("PORT") {
            format!("0.0.0.0:{port}").parse()?
        } else {
            std::env::var("LISTEN_ADDR")
                .unwrap_or_else(|_| "0.0.0.0:3001".into())
                .parse()?
        };

        let validation_identity_program = resolve_validation_identity_program(
            std::env::var("VALIDATION_IDENTITY_PROGRAM_ID")
                .ok()
                .as_deref(),
            listen_addr,
            environment,
        )?;

        let api_keys: Vec<String> = match std::env::var("API_KEYS") {
            Ok(s) => serde_json::from_str(&s)
                .map_err(|e| format!("API_KEYS contains invalid JSON: {e}"))?,
            Err(_) => vec![],
        };

        let rate_limit_per_minute: u32 = match std::env::var("RATE_LIMIT_PER_MINUTE") {
            Ok(s) => s
                .parse()
                .map_err(|e| format!("RATE_LIMIT_PER_MINUTE is not a valid u32: {e}"))?,
            Err(_) => 60,
        };

        let study_rate_limit_per_minute: u32 = match std::env::var("STUDY_RATE_LIMIT_PER_MINUTE") {
            Ok(s) => s
                .parse()
                .map_err(|e| format!("STUDY_RATE_LIMIT_PER_MINUTE is not a valid u32: {e}"))?,
            Err(_) => 600,
        };
        if !(1..=10_000).contains(&study_rate_limit_per_minute) {
            return Err("STUDY_RATE_LIMIT_PER_MINUTE must be between 1 and 10000".into());
        }

        let study_max_in_flight: usize = match std::env::var("STUDY_MAX_IN_FLIGHT") {
            Ok(s) => s
                .parse()
                .map_err(|e| format!("STUDY_MAX_IN_FLIGHT is not a valid usize: {e}"))?,
            Err(_) => 32,
        };
        if !(1..=256).contains(&study_max_in_flight) {
            return Err("STUDY_MAX_IN_FLIGHT must be between 1 and 256".into());
        }

        let per_ip_rate_limit_per_minute: u32 =
            match std::env::var("EXECUTOR_PER_IP_RATE_LIMIT_PER_MIN") {
                Ok(s) => s.parse().map_err(|e| {
                    format!("EXECUTOR_PER_IP_RATE_LIMIT_PER_MIN is not a valid u32: {e}")
                })?,
                Err(_) => 30,
            };

        let integrators: Vec<IntegratorConfig> = match std::env::var("INTEGRATORS") {
            Ok(s) => serde_json::from_str(&s)
                .map_err(|e| format!("INTEGRATORS contains invalid JSON: {e}"))?,
            Err(_) => vec![],
        };

        let api_keys = if api_keys.is_empty() && !integrators.is_empty() {
            integrators.iter().map(|i| i.api_key.clone()).collect()
        } else {
            api_keys
        };

        let cors_origin_values: Vec<String> = match std::env::var("CORS_ORIGINS") {
            Ok(s) => serde_json::from_str(&s)
                .map_err(|e| format!("CORS_ORIGINS contains invalid JSON: {e}"))?,
            Err(_) => vec![],
        };
        let cors_origins = parse_cors_origins(cors_origin_values, environment)?;

        let sas_authority_keypair = if let Ok(json) = std::env::var("SAS_AUTHORITY_KEYPAIR") {
            let bytes: Vec<u8> = serde_json::from_str(&json)
                .map_err(|e| format!("SAS_AUTHORITY_KEYPAIR is not valid JSON: {e}"))?;
            Some(
                Keypair::try_from(bytes.as_slice())
                    .map_err(|e| format!("SAS_AUTHORITY_KEYPAIR contains invalid keypair: {e}"))?,
            )
        } else if let Ok(path) = std::env::var("SAS_AUTHORITY_KEYPAIR_PATH") {
            Some(
                read_keypair_file(&path).map_err(|e| {
                    format!("Failed to read SAS authority keypair from {path}: {e}")
                })?,
            )
        } else {
            None
        };

        let sas_credential_pda = std::env::var("SAS_CREDENTIAL_PDA")
            .ok()
            .and_then(|s| Pubkey::from_str(&s).ok());

        let sas_schema_pda = std::env::var("SAS_SCHEMA_PDA")
            .ok()
            .and_then(|s| Pubkey::from_str(&s).ok());

        let sas_attestation_ttl_days: u64 = std::env::var("SAS_ATTESTATION_TTL_DAYS")
            .ok()
            .and_then(|s| s.parse().ok())
            .unwrap_or(30);

        let validation_service_url = std::env::var("VALIDATION_SERVICE_URL").ok();
        let validation_service_url_signature =
            std::env::var("VALIDATION_SERVICE_URL_SIGNATURE").ok();
        let validation_api_key = std::env::var("VALIDATION_API_KEY").ok();

        let challenge_ttl_secs =
            parse_challenge_ttl_secs(std::env::var("CHALLENGE_TTL_SECS").ok().as_deref())?;

        // Default 5 attempts / 1h. Permissive at launch — tightenable
        // via env var once we have real-user failure-rate data.
        let wallet_max_attempts: u8 = std::env::var("VALIDATION_WALLET_MAX_ATTEMPTS")
            .ok()
            .and_then(|s| s.parse().ok())
            .unwrap_or(5);

        let wallet_window_secs: u64 = std::env::var("VALIDATION_WALLET_WINDOW_SECS")
            .ok()
            .and_then(|s| s.parse().ok())
            .unwrap_or(3600);

        // Observe-first: both default ON so we collect calibration data as soon
        // as SDKs/traffic provide the signal. Set `=false` (or `0`/`no`/`off`)
        // to silence. An unrecognized value KEEPS the default rather than
        // silently disabling the signal on a typo; resolved values are logged at
        // startup in main.rs.
        let automation_observe = parse_bool_env("EXECUTOR_AUTOMATION_OBSERVE", true);
        let automation_webdriver_reject =
            parse_bool_env("EXECUTOR_AUTOMATION_WEBDRIVER_REJECT", true);
        let wallet_reputation_observe = parse_bool_env("EXECUTOR_WALLET_REPUTATION_OBSERVE", true);
        let curve_trace_observe = parse_bool_env("EXECUTOR_CURVE_TRACE_OBSERVE", true);

        let cross_wallet_cooldown_secs: u64 =
            std::env::var("VALIDATION_CROSS_WALLET_COOLDOWN_SECS")
                .ok()
                .and_then(|s| s.parse().ok())
                .unwrap_or(86400);

        let cross_wallet_cooldown_enforce =
            parse_bool_env("VALIDATION_CROSS_WALLET_COOLDOWN_ENFORCE", false);

        Ok(Config {
            environment,
            rpc_url,
            validation_identity_program,
            ws_url,
            relayer_keypair,
            sas_authority_keypair,
            listen_addr,
            api_keys,
            rate_limit_per_minute,
            study_rate_limit_per_minute,
            study_max_in_flight,
            per_ip_rate_limit_per_minute,
            integrators,
            cors_origins,
            sas_credential_pda,
            sas_schema_pda,
            sas_attestation_ttl_days,
            validation_service_url,
            validation_service_url_signature,
            validation_api_key,
            challenge_ttl_secs,
            wallet_max_attempts,
            wallet_window_secs,
            automation_observe,
            automation_webdriver_reject,
            wallet_reputation_observe,
            curve_trace_observe,
            cross_wallet_cooldown_secs,
            cross_wallet_cooldown_enforce,
            scoring_config,
        })
    }
}

fn resolve_validation_identity_program(
    value: Option<&str>,
    listen_addr: SocketAddr,
    environment: Environment,
) -> Result<Pubkey, String> {
    let program = value
        .map(Pubkey::from_str)
        .transpose()
        .map_err(|_| "VALIDATION_IDENTITY_PROGRAM_ID must be a public key".to_string())?
        .unwrap_or_else(crate::solana::pda::anchor_program_id);
    if program == Pubkey::default() {
        return Err("VALIDATION_IDENTITY_PROGRAM_ID cannot be the system program".into());
    }
    if program != crate::solana::pda::anchor_program_id() && !listen_addr.ip().is_loopback() {
        return Err("An alternate validation identity program requires a loopback listener".into());
    }
    if program != crate::solana::pda::anchor_program_id() && !environment.is_prod() {
        return Err("An alternate validation identity program requires ENVIRONMENT=prod".into());
    }
    Ok(program)
}

#[cfg(test)]
mod validation_identity_tests {
    use super::*;
    #[test]
    fn alternate_program_requires_loopback_and_valid_key() {
        let public = "0.0.0.0:3001".parse().expect("address");
        let local = "127.0.0.1:3001".parse().expect("address");
        let alternate = Pubkey::new_unique().to_string();
        assert_eq!(
            resolve_validation_identity_program(None, public, Environment::Dev).expect("default"),
            crate::solana::pda::anchor_program_id()
        );
        assert!(
            resolve_validation_identity_program(Some(&alternate), public, Environment::Prod)
                .is_err()
        );
        assert!(
            resolve_validation_identity_program(Some(&alternate), local, Environment::Prod).is_ok()
        );
        assert!(
            resolve_validation_identity_program(Some(&alternate), local, Environment::Dev).is_err()
        );
        assert!(
            resolve_validation_identity_program(Some("bad"), local, Environment::Prod).is_err()
        );
        assert!(resolve_validation_identity_program(
            Some(&Pubkey::default().to_string()),
            local,
            Environment::Prod
        )
        .is_err());
    }
}
